name:                generate
version:             0.1.0.0
github:              "haskell-works/generate"
license:             BSD3
author:              "John Ky"
maintainer:          "newhoggy@gmail.com"
copyright:           "2018 John Ky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/haskell-works/generate#readme>

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5
- binary
- bits-extra
- bytestring
- hw-bits
- hw-prim
- lens
- parallel
- mmap
- prettyprinter
- split
- text
- vector
- word8

library:
  build-tools:
  - c2hs
  source-dirs: src

executables:
  generate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generate
    - optparse-applicative

tests:
  generate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generate

flags:
  sse42:
    description: Enable SSE 4.2 optimisations.
    manual: false
    default: true

  bmi2:
    description: Enable bmi2 instruction set
    manual: false
    default: false

  avx2:
    description: Enable avx2 instruction set
    manual: false
    default: false
